//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MP3_Tag.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MP3_Tag.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The property Error from IDataErrorInfo is not supported. Use -this- indexer instead. ähnelt.
        /// </summary>
        public static string BindableValidator_IDataErrorInfo_PropertyErrorNotSupported {
            get {
                return ResourceManager.GetString("BindableValidator_IDataErrorInfo_PropertyErrorNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear Albums ähnelt.
        /// </summary>
        public static string CheckedElementsVM_DisplayName_ClearAlbum {
            get {
                return ResourceManager.GetString("CheckedElementsVM_DisplayName_ClearAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove ähnelt.
        /// </summary>
        public static string CheckedElementsVM_DisplayName_Remove {
            get {
                return ResourceManager.GetString("CheckedElementsVM_DisplayName_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rename ähnelt.
        /// </summary>
        public static string CheckedElementsVM_DisplayName_Rename {
            get {
                return ResourceManager.GetString("CheckedElementsVM_DisplayName_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string CheckedElementsVM_DisplayName_Save {
            get {
                return ResourceManager.GetString("CheckedElementsVM_DisplayName_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Undo ähnelt.
        /// </summary>
        public static string CheckedElementsVM_DisplayName_Undo {
            get {
                return ResourceManager.GetString("CheckedElementsVM_DisplayName_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CB_All ähnelt.
        /// </summary>
        public static string CommandBroadcast_All {
            get {
                return ResourceManager.GetString("CommandBroadcast_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CB_Checked ähnelt.
        /// </summary>
        public static string CommandBroadcast_Checked {
            get {
                return ResourceManager.GetString("CommandBroadcast_Checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die C_Add ähnelt.
        /// </summary>
        public static string CommandName_Add {
            get {
                return ResourceManager.GetString("CommandName_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die C_ClearAlbum ähnelt.
        /// </summary>
        public static string CommandName_ClearAlbum {
            get {
                return ResourceManager.GetString("CommandName_ClearAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die C_Load ähnelt.
        /// </summary>
        public static string CommandName_Load {
            get {
                return ResourceManager.GetString("CommandName_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die C_Remove ähnelt.
        /// </summary>
        public static string CommandName_Remove {
            get {
                return ResourceManager.GetString("CommandName_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die C_Rename ähnelt.
        /// </summary>
        public static string CommandName_Rename {
            get {
                return ResourceManager.GetString("CommandName_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die C_Save ähnelt.
        /// </summary>
        public static string CommandName_Save {
            get {
                return ResourceManager.GetString("CommandName_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die C_Undo ähnelt.
        /// </summary>
        public static string CommandName_Undo {
            get {
                return ResourceManager.GetString("CommandName_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file could not be added. ähnelt.
        /// </summary>
        public static string DataGridVM_Exception_Add {
            get {
                return ResourceManager.GetString("DataGridVM_Exception_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file could not be removed from the list. ähnelt.
        /// </summary>
        public static string DataGridVM_Exception_Remove {
            get {
                return ResourceManager.GetString("DataGridVM_Exception_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passed path parameter: {0} ähnelt.
        /// </summary>
        public static string DataGridVM_Inner_Exception_Add {
            get {
                return ResourceManager.GetString("DataGridVM_Inner_Exception_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File path of mp3 file: {0} ähnelt.
        /// </summary>
        public static string DataGridVM_Inner_Exception_Remove {
            get {
                return ResourceManager.GetString("DataGridVM_Inner_Exception_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The wished command does not exist. ähnelt.
        /// </summary>
        public static string Exception_InvalidCommandName {
            get {
                return ResourceManager.GetString("Exception_InvalidCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file could not be deleted. ähnelt.
        /// </summary>
        public static string FileModifierM_Exception_Delete {
            get {
                return ResourceManager.GetString("FileModifierM_Exception_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file could not be renamed. ähnelt.
        /// </summary>
        public static string FileModifierM_Exception_Move {
            get {
                return ResourceManager.GetString("FileModifierM_Exception_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passed path parameter: {0} ähnelt.
        /// </summary>
        public static string FileModifierM_Inner_Exception_Delete {
            get {
                return ResourceManager.GetString("FileModifierM_Inner_Exception_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passed path parameter (old): {0}\n\nPassed path parameter (new): {1} ähnelt.
        /// </summary>
        public static string FileModifierM_Inner_Exception_Move {
            get {
                return ResourceManager.GetString("FileModifierM_Inner_Exception_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_add {
            get {
                object obj = ResourceManager.GetObject("img_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_changed {
            get {
                object obj = ResourceManager.GetObject("img_changed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_clearAlbum {
            get {
                object obj = ResourceManager.GetObject("img_clearAlbum", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_delete {
            get {
                object obj = ResourceManager.GetObject("img_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_eject {
            get {
                object obj = ResourceManager.GetObject("img_eject", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_ok {
            get {
                object obj = ResourceManager.GetObject("img_ok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_pause {
            get {
                object obj = ResourceManager.GetObject("img_pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_play {
            get {
                object obj = ResourceManager.GetObject("img_play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_save {
            get {
                object obj = ResourceManager.GetObject("img_save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_stop {
            get {
                object obj = ResourceManager.GetObject("img_stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap img_undo {
            get {
                object obj = ResourceManager.GetObject("img_undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add ähnelt.
        /// </summary>
        public static string MenuVM_DisplayName_Add {
            get {
                return ResourceManager.GetString("MenuVM_DisplayName_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear all albums ähnelt.
        /// </summary>
        public static string MenuVM_DisplayName_ClearAlbum {
            get {
                return ResourceManager.GetString("MenuVM_DisplayName_ClearAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove all ähnelt.
        /// </summary>
        public static string MenuVM_DisplayName_Remove {
            get {
                return ResourceManager.GetString("MenuVM_DisplayName_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save all ähnelt.
        /// </summary>
        public static string MenuVM_DisplayName_Save {
            get {
                return ResourceManager.GetString("MenuVM_DisplayName_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Undo all ähnelt.
        /// </summary>
        public static string MenuVM_DisplayName_Undo {
            get {
                return ResourceManager.GetString("MenuVM_DisplayName_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear Album ähnelt.
        /// </summary>
        public static string Mp3SongVM_DisplayName_ClearAlbum {
            get {
                return ResourceManager.GetString("Mp3SongVM_DisplayName_ClearAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load ähnelt.
        /// </summary>
        public static string Mp3SongVM_DisplayName_Load {
            get {
                return ResourceManager.GetString("Mp3SongVM_DisplayName_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove ähnelt.
        /// </summary>
        public static string Mp3SongVM_DisplayName_Remove {
            get {
                return ResourceManager.GetString("Mp3SongVM_DisplayName_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string Mp3SongVM_DisplayName_Save {
            get {
                return ResourceManager.GetString("Mp3SongVM_DisplayName_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Undo ähnelt.
        /// </summary>
        public static string Mp3SongVM_DisplayName_Undo {
            get {
                return ResourceManager.GetString("Mp3SongVM_DisplayName_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file could not be loaded. ähnelt.
        /// </summary>
        public static string TagLibMp3File_Exception_InvalidFilePath {
            get {
                return ResourceManager.GetString("TagLibMp3File_Exception_InvalidFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passed path parameter: {0} ähnelt.
        /// </summary>
        public static string TagLibMp3File_Inner_Exception_InvalidFilePath {
            get {
                return ResourceManager.GetString("TagLibMp3File_Inner_Exception_InvalidFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The field &quot;{0}&quot; contains an invalid character! ähnelt.
        /// </summary>
        public static string Validation_Error_InvalidCharacter {
            get {
                return ResourceManager.GetString("Validation_Error_InvalidCharacter", resourceCulture);
            }
        }
    }
}
